all: CachingSolver.o NoSuspectFourUnknownsLikelihoodSolver.o \
            NoSuspectOneUnknownLikelihoodSolver.o \
            NoSuspectThreeUnknownsLikelihoodSolver.o \
            NoSuspectTwoUnknownsLikelihoodSolver.o \
            OneSuspectNoUnknownsLikelihoodSolver.o \
            OneSuspectOneUnknownLikelihoodSolver.o \
            OneSuspectThreeUnknownsLikelihoodSolver.o \
            OneSuspectTwoUnknownsLikelihoodSolver.o \
            UnknownsSolver.o LikelihoodSolver.o

CachingSolver.o: CachingSolver.cpp
	g++ -I ../../lib/boost_1_53_0 -g -c CachingSolver.cpp

NoSuspectFourUnknownsLikelihoodSolver.o: NoSuspectFourUnknownsLikelihoodSolver.cpp
	g++ -I ../../lib/boost_1_53_0 -g -c NoSuspectFourUnknownsLikelihoodSolver.cpp

NoSuspectOneUnknownLikelihoodSolver.o: NoSuspectOneUnknownLikelihoodSolver.cpp
	g++ -I ../../lib/boost_1_53_0 -g -c NoSuspectOneUnknownLikelihoodSolver.cpp

NoSuspectThreeUnknownsLikelihoodSolver.o: NoSuspectThreeUnknownsLikelihoodSolver.cpp
	g++ -I ../../lib/boost_1_53_0 -g -c NoSuspectThreeUnknownsLikelihoodSolver.cpp

NoSuspectTwoUnknownsLikelihoodSolver.o: NoSuspectTwoUnknownsLikelihoodSolver.cpp
	g++ -I ../../lib/boost_1_53_0 -g -c NoSuspectTwoUnknownsLikelihoodSolver.cpp

OneSuspectNoUnknownsLikelihoodSolver.o: OneSuspectNoUnknownsLikelihoodSolver.cpp
	g++ -I ../../lib/boost_1_53_0 -g -c OneSuspectNoUnknownsLikelihoodSolver.cpp

OneSuspectOneUnknownLikelihoodSolver.o: OneSuspectOneUnknownLikelihoodSolver.cpp
	g++ -I ../../lib/boost_1_53_0 -g -c OneSuspectOneUnknownLikelihoodSolver.cpp

OneSuspectThreeUnknownsLikelihoodSolver.o: OneSuspectThreeUnknownsLikelihoodSolver.cpp
	g++ -I ../../lib/boost_1_53_0 -g -c OneSuspectThreeUnknownsLikelihoodSolver.cpp

OneSuspectTwoUnknownsLikelihoodSolver.o: OneSuspectTwoUnknownsLikelihoodSolver.cpp
	g++ -I ../../lib/boost_1_53_0 -g -c OneSuspectTwoUnknownsLikelihoodSolver.cpp

UnknownsSolver.o: UnknownsSolver.cpp
	g++ -I ../../lib/boost_1_53_0 -g -c UnknownsSolver.cpp

LikelihoodSolver.o: LikelihoodSolver.cpp
	g++ -I ../../lib/boost_1_53_0 -g -c LikelihoodSolver.cpp
