all: DebugUtil.o FileReaderUtil.o LikelihoodUtil.o ProbabilityUtil.o

DebugUtil.o: DebugUtil.cpp
	g++ -I ../../lib/boost_1_53_0 -g -c DebugUtil.cpp

FileReaderUtil.o: FileReaderUtil.cpp
	g++ -I ../../lib/boost_1_53_0 -g -c FileReaderUtil.cpp

LikelihoodUtil.o: LikelihoodUtil.cpp
	g++ -I ../../lib/boost_1_53_0 -g -c LikelihoodUtil.cpp

ProbabilityUtil.o: ProbabilityUtil.cpp
	g++ -I ../../lib/boost_1_53_0 -g -c ProbabilityUtil.cpp
